services:
  etcd:
    image: quay.io/coreos/etcd:v3.5.12
    command:
      - /usr/local/bin/etcd
      - --advertise-client-urls=http://0.0.0.0:2379
      - --listen-client-urls=http://0.0.0.0:2379
      - --data-dir=/var/lib/etcd
    ports:
      - "2379:2379"

  apisix:
    image: apache/apisix:latest
    depends_on: [ etcd ]
    volumes:
      - ./apisix/conf/config.yaml:/usr/local/apisix/conf/config.yaml
    ports:
      - "9080:9080"
      - "9180:9180"
    extra_hosts:
      - "host.docker.internal:host-gateway"
